### ISSUE TITLE
Connect to ESP-udp-neo-OTA-webconfig

### ISSUE THREAD

**Issue by mabushey** [penfold42/stuff#2]
Thanks for the help compiling this. :) I connected to the `WS2812-68fb9` ssid with my cell, and it redirected me to a captive portal where I selected my ssid and entered the pass. I have an IP from the DHCP server, but the serial terminal is pretty dead. When I go to the IP I get this returned to the browser: `Not found: /`. The esp boots up, flashes the LEDs a bit quickly, and then turns the LED's green (// green is good).

The first time in the serial console there was a dump of the SSID's it found scanning, and then it said connecting. Colorchord (another esp8266 project) barfs connecting to my wifi (IPv4, WPA2 PSK (TKIP, CCMP), I wonder if there's a bug in the WIFI libraries when there's nonalphanumeric charaters in the password. Obviously we are connecting as `Not found: /` is returned in the browser.

I was having issues missing the initial serial output so I used this: `while :; do find /dev -name "ttyUSB*" -exec screen {} 115200 \;; done`. After plugging in the esp8266 this comes up:

```
Chip ID: 0x68FB9
Hostname: WS
            *WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
```

**Comment by penfold42** [comment]
Sorry for the delay - I missed the notification!

It sounds like it's working - I don't think I ever did a page on / or /index.html

Try browsing to http://<ip>/status
